### ISSUE TITLE
Research Back-End Services

### ISSUE THREAD

**Issue by nooraniali17** [nooraniali17/BusMe#4]
Amazon Web Services
Microsoft Azure
Google Cloud Platform

**Comment by xsduan** [comment]
DigitalOcean is usually on the cheaper side, though it has fewer services.

**Comment by xsduan** [comment]
chose poetry and flask

**Comment by xsduan** [comment]
aiohttp instead of flask

**Comment by xsduan** [comment]
backend technologies have already been selected. further requests for changes should be discussed individually.
