### ISSUE TITLE
Research Database Technologies

### ISSUE THREAD

**Issue by nooraniali17** [nooraniali17/BusMe#7]

**Comment by xsduan** [comment]
[PonyORM](https://ponyorm.org/) is extremely simple to use imo, and will allow us to switch between MySQL, Postgres, MSSQL, and a few others at will. However we're probably only going to consider MySQL and Postgres.

**Comment by xsduan** [comment]
using peewee-async

**Comment by xsduan** [comment]
if further replacement is needed, a new issue should be opened.
